version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - dependabot
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.12.6
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: kth-node-mongo
    versions:
    - 3.3.10
    - 3.3.8
    - 3.3.9
  - dependency-name: swagger-ui
    versions:
    - 3.41.1
    - 3.42.0
    - 3.43.0
    - 3.44.0
    - 3.44.1
    - 3.45.0
    - 3.45.1
    - 3.46.0
  - dependency-name: kth-node-express-routing
    versions:
    - 2.0.4
    - 2.0.5
    - 2.0.6
  - dependency-name: "@kth/in-memory-cache"
    versions:
    - 0.1.20
    - 0.1.21
    - 0.1.22
    - 0.1.23
    - 0.1.24
    - 0.1.25
    - 0.1.26
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.3
  - dependency-name: applicationinsights
    versions:
    - 1.8.10
    - 1.8.9
  - dependency-name: kth-node-api-common
    versions:
    - 1.0.2
    - 1.0.3
    - 1.0.4
  - dependency-name: kth-node-monitor
    versions:
    - 1.1.9
