version: '3'
services:

  web:

    env_file:
      - .env

    environment: 
      MONGODB_COLLECTION: "flottsbro-api"
      
    build: .

    ports:
      - 3001:3001

    labels:
      - se.kth.cluster=${PORTILLO_CLUSTER}
      - se.kth.slackChannels=#team-pipeline-build
      - se.kth.importance=low
