version: "3"

services:
  #############################################
  # Start API on http://api:3001/api/pipeline
  #############################################
  api:
    image: $LOCAL_IMAGE_ID
    environment:
      - LOGGING_LEVEL=warn
      - API_KEYS_0
      - API_KEYS_1
      - MONGODB_CONNECTION_STRING
      - MONGODB_COLLECTION
    ports:
      - 3001

  #############################################
  # Start the client running tests
  # agains http://api:3001/api/pipeline
  #############################################
  integration-tests:
    build: ./tests/integration-tests
    environment:
      - FLOTTSBRO_API_KEY

    depends_on:
      - api
