version: '3'
services:

  web:

    env_file:
      - .env

    environment: 
      MONGODB_COLLECTION: "flottsbro-api"
      APPINSIGHTS_INSTRUMENTATIONKEY: "4f0c0a71-b822-4e20-84c0-97150af3f0a9"
      
    build: .

    ports:
      - 3001:3001

    labels:
      - se.kth.cluster=${PORTILLO_CLUSTER}
      - se.kth.slackChannels=#team-pipeline-build
      - se.kth.importance=low
