version: "3"

#
# Run this integration test by running:
# ID=$(docker build -q .) && LOCAL_IMAGE_ID=$ID docker-compose -f docker-compose-integration-tests.yml up --abort-on-container-exit --always-recreate-deps
#
# docker images | grep kth-azure-app_app | awk '{ print $3 }' | xargs docker inspect | grep se.kth.imageVersion
services:
  #############################################
  # Start http://api:3000/
  #############################################
  api:
    # if not --build and kth-azure-app already exists in
    # your local computers registry 'image' is used.
    image: $LOCAL_IMAGE_ID

    env_file: 
      - .env

    environment:
      - LOGGING_LEVEL=warn
      
    ports:
      - 3001

  #############################################
  # Start the client running tests
  # agains http://api:3000/
  #############################################
  integration-tests:
    # Build client image and run tests
    # from inside that.
    build: ${WORKSPACE}/tests/integration-tests
    env_file: 
      - .env

    depends_on:
      - api
